### ISSUE TITLE
Fix the current Behat tests

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#3]
I've created some Behat tests with the functionality, I wish to be present. Without changing the Behat Tests, can you get this working?

**Comment by mglaman** [comment]
Need to implement *And I should see "View my registration" *. 

I have no idea why *Then I should not see "Please set your contact information on your profile page"* is failing. Might be a session issue.

**Comment by mglaman** [comment]
All that's left is one more. And it's failing because Drupal's holding onto some stale messages. If we added a "refresh" step the test would pass. However going to see if we can just get the messages to not show.

![screenshot from 2015-03-28 23 33 53](https://cloud.githubusercontent.com/assets/3698644/6884117/ecab2228-d5a2-11e4-84be-62f320be7a59.png)

**Comment by mglaman** [comment]
Upgrading to Commons 3.23 will bring in Features 2.4 and fix foreign keys issue.
